function s= showOrientation(filename, echoes)
% function s= showOrientation(filename[, echoes])
% 
% This will plot in 3D a vector being rotated by the matrices
% specified in a kviews.txt file, as generated by the scanner
%
% filename - specify which rotations file you want
% echoes - specify which echor (rotations) you want to see in the file.  if
% not specify, it will display them all
%
kv=load(filename);

if nargin<2
	echoes=1:size(kv,1);
end

unit = [1 0 1]
s=zeros(length(echoes), 3);

for n=echoes
	tmp = kv(n, end-8:end);
	R = reshape(tmp',3,3)';
	s(n,:) = unit*R';
end

plot3(s(:,1), s(:,2), s(:,3), 'o');
axis square
drawnow
whos s
end
